export const API_PREFIX = '/api/v1';

/** Default upload chunk size. Must stay well under Cloudflare's 100 MB request-body limit. */
export const DEFAULT_CHUNK_SIZE = 32 * 1024 * 1024;

/** Thumbnail edge lengths generated by the worker. 256 for grids, 1600 for previews. */
export const THUMB_SIZES = [256, 1600] as const;
export type ThumbSize = (typeof THUMB_SIZES)[number];

export const NAME_MAX_LENGTH = 255;

/** Older versions kept per file; the oldest goes when a file is saved again (like Google Drive's 100). */
export const MAX_VERSIONS_PER_FILE = 50;
export const PASSWORD_MIN_LENGTH = 10;
export const PASSWORD_MAX_LENGTH = 256;

export const PAGE_SIZE_DEFAULT = 200;
export const PAGE_SIZE_MAX = 500;

export const KiB = 1024;
export const MiB = 1024 * KiB;
export const GiB = 1024 * MiB;
export const TiB = 1024 * GiB;

/** Custom logo uploaded in Admin → Branding. */
export const BRAND_LOGO_TYPES = ['image/svg+xml', 'image/png', 'image/webp'] as const;
export const BRAND_LOGO_MAX_BYTES = 256 * 1024;
