#!/usr/bin/env bash
# Family Cloud installer: prepares storage folders, writes deploy/.env with fresh secrets and
# starts the stack with Docker Compose. Safe to re-run: existing settings are kept.
#
#   ./scripts/install.sh                   interactive
#   ./scripts/install.sh --install-docker  also install Docker Engine (Ubuntu/Debian, uses sudo)
#
# Non-interactive: PUBLIC_URL=https://cloud.example.com CLOUDFLARE_TUNNEL_TOKEN=... ./scripts/install.sh -y
# WAIT_SECS=600 gives a slow machine longer to start the first time (default 180).
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
# shellcheck source=scripts/lib.sh
. "$ROOT/scripts/lib.sh"
ENV_FILE="$ROOT/deploy/.env"
YES=false
INSTALL_DOCKER=false
for arg in "$@"; do
  case "$arg" in
    -y|--yes) YES=true ;;
    --install-docker) INSTALL_DOCKER=true ;;
    -h|--help) sed -n '2,9p' "$0"; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; exit 1 ;;
  esac
done

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
die() { printf '\033[31mError:\033[0m %s\n' "$*" >&2; exit 1; }
ask() { # ask VAR "Question" "default"
  local var=$1 q=$2 def=${3:-} ans
  if [[ -n "${!var:-}" ]]; then return; fi
  if $YES; then printf -v "$var" '%s' "$def"; return; fi
  read -r -p "  $q${def:+ [$def]}: " ans || true
  printf -v "$var" '%s' "${ans:-$def}"
}
rand() { openssl rand -hex 32; }

bold "Family Cloud installer"

[[ "$(uname -s)" == "Linux" ]] || die "This installer supports Linux hosts."
command -v openssl >/dev/null || die "openssl is required (sudo apt install openssl)."

if ! command -v docker >/dev/null; then
  if $INSTALL_DOCKER; then
    bold "Installing Docker Engine (sudo required)…"
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker "$USER"
    info "Added $USER to the docker group. Log out and back in (or run: newgrp docker), then re-run this script."
    exit 0
  fi
  die "Docker is not installed. Re-run with --install-docker, or see https://docs.docker.com/engine/install/"
fi
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 plugin is required (docker compose version)."
docker info >/dev/null 2>&1 || die "Can't talk to Docker. Is your user in the docker group? (sudo usermod -aG docker \$USER, then log in again)"

# Keep existing values on re-runs (read safely: the file is never executed).
if [[ -f "$ENV_FILE" ]]; then
  load_env "$ENV_FILE"
  bold "Found existing deploy/.env; keeping its settings."
fi

bold "Settings"
ask PUBLIC_URL "Address family members will use" "https://cloud.example.com"
ask APP_NAME "Name shown in the app" "Family Cloud"
ask STORAGE_ROOT "Where to keep files and the database" "/srv/familycloud"
ask CLOUDFLARE_TUNNEL_TOKEN "Cloudflare Tunnel token (leave empty to add later)" ""
[[ "$PUBLIC_URL" =~ ^https?://[^[:space:]]+$ ]] || die "PUBLIC_URL must look like https://cloud.example.com (http:// only for LAN testing)."
(( ${#APP_NAME} >= 1 && ${#APP_NAME} <= 60 )) || die "The app name must be 1-60 characters."
[[ "$STORAGE_ROOT" == /* ]] || die "The storage location must be an absolute path (e.g. /srv/familycloud)."

SECRET_KEY=${SECRET_KEY:-$(rand)}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-$(rand)}
PUID=${PUID:-$(id -u)}
PGID=${PGID:-$(id -g)}

bold "Preparing $STORAGE_ROOT"
for d in volumes/disk1 cache db backups; do
  if [[ ! -d "$STORAGE_ROOT/$d" ]]; then
    sudo mkdir -p "$STORAGE_ROOT/$d"
  fi
done
sudo chown "$PUID:$PGID" "$STORAGE_ROOT" "$STORAGE_ROOT/volumes" "$STORAGE_ROOT/volumes/disk1" "$STORAGE_ROOT/cache" "$STORAGE_ROOT/backups"
sudo chmod 750 "$STORAGE_ROOT"
info "volumes/disk1  file data (first disk)"
info "db             database"
info "cache          thumbnails"

# Write to a private temp file, then move it into place: the result is mode 600 even if an
# older deploy/.env had looser permissions, and a failed write never leaves a half file.
TMP_ENV=$(mktemp "$ROOT/deploy/.env.XXXXXX")
trap 'rm -f "$TMP_ENV"' EXIT
chmod 600 "$TMP_ENV"
{
  echo "# Generated by scripts/install.sh on $(date -u +%Y-%m-%d). Keep this file private."
  env_line PUBLIC_URL "$PUBLIC_URL"
  env_line APP_NAME "$APP_NAME"
  env_line SECRET_KEY "$SECRET_KEY"
  env_line POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
  env_line STORAGE_ROOT "$STORAGE_ROOT"
  env_line PUID "$PUID"
  env_line PGID "$PGID"
  env_line CLOUDFLARE_TUNNEL_TOKEN "$CLOUDFLARE_TUNNEL_TOKEN"
  env_line DOMAIN "${DOMAIN:-}"
  env_line APP_PORT "${APP_PORT:-3080}"
  env_line IMAGE "${IMAGE:-ghcr.io/amoghkaja/cloud-storage:latest}"
  env_line LOG_LEVEL "${LOG_LEVEL:-info}"
} > "$TMP_ENV" || die "Could not write deploy/.env (see the message above)."
mv "$TMP_ENV" "$ENV_FILE"
chmod 600 "$ENV_FILE"
trap - EXIT
info "Wrote deploy/.env (secrets generated, permissions 600)."

cd "$ROOT/deploy"
PROFILE=()
[[ -n "$CLOUDFLARE_TUNNEL_TOKEN" ]] && PROFILE=(--profile tunnel)

bold "Starting Family Cloud"
if ! docker compose pull --quiet app 2>/dev/null; then
  info "No published image available; building locally (takes a few minutes)…"
  docker compose build app
fi
docker compose "${PROFILE[@]}" up -d

printf '  Waiting for the app to start'
READY=false
WAIT_SECS=${WAIT_SECS:-180}   # first start on slow hardware (e.g. a Pi) may need longer
for _ in $(seq 1 $((WAIT_SECS / 2))); do
  if curl -fsS "http://127.0.0.1:${APP_PORT:-3080}/healthz" >/dev/null 2>&1; then READY=true; echo " ready."; break; fi
  printf '.'; sleep 2
done
if ! $READY; then
  echo
  printf '\033[31mThe app did not become healthy within %ss.\033[0m Recent logs:\n' "$WAIT_SECS" >&2
  docker compose "${PROFILE[@]}" ps >&2 || true
  docker compose logs --tail 40 app worker db >&2 || true
  die "Fix the problem shown above, then re-run ./scripts/install.sh (your settings are kept)."
fi

if ! TOKEN=$(docker compose exec -T app node dist/cli.js setup-token 2>&1 | tail -1); then
  TOKEN=""
  info "Couldn't read the setup token automatically. Get it with:"
  info "  cd deploy && docker compose exec app node dist/cli.js setup-token"
fi
echo
bold "Done!"
if [[ "$TOKEN" != Setup* && -n "$TOKEN" ]]; then
  info "Open $PUBLIC_URL/setup and create the admin account."
  info "Setup token: $TOKEN"
else
  info "Open $PUBLIC_URL and sign in."
fi
[[ -z "$CLOUDFLARE_TUNNEL_TOKEN" ]] && info "No tunnel token yet: the app is only on http://127.0.0.1:${APP_PORT:-3080}. See docs/cloudflare-tunnel.md."
info "Next: set up backups (docs/backup-restore.md)."
